### ISSUE TITLE
Does not work with Co-Hosting

### ISSUE THREAD

**Issue by shersh** [OrleansContrib/Orleans.Redis#16]
When we use orleans co-hosting with ASP.NET we do not have ISiloHostBuild and have only ISiloBuilder. 
So we can't use extensions like AddRedisGrainStorage.

**Comment by ReubenBond** [comment]
@shersh it should be available: https://github.com/OrleansContrib/Orleans.Redis/blob/fc56a6aad1b2084949ddf5f119a3f5244b9327bd/src/Orleans.Persistence.Redis/RedisPersistenceHostingExtensions.cs#L63

**Comment by shersh** [comment]
Hmm, yes, thanks. 
I have updated nuget packet and see these methods via intellisense. Hmm. 
I will close issue
