### ISSUE TITLE
'ISiloBuilder' does not contain a definition for 'AddRedisGrainStorage'

### ISSUE THREAD

**Issue by dodyg** [OrleansContrib/Orleans.Redis#5]
![working](https://user-images.githubusercontent.com/1761249/89099906-0a354b80-d3f3-11ea-9542-ecf14105d938.png)
![working-2](https://user-images.githubusercontent.com/1761249/89099909-0e616900-d3f3-11ea-910a-09e087b02bcb.png)

Although according to https://github.com/OrleansContrib/Orleans.Redis/blob/15b63ca48f11b715c6d05da1a60e85c9f8812247/src/Orleans.Persistence.Redis/RedisPersistenceHostingExtensions.cs#L79, this should compile. 

Am I using the wrong nuget source?

**Comment by ReubenBond** [comment]
Is your code in a branch somewhere? I need to set up publishing for this package

**Comment by dodyg** [comment]
Thanks. My code is here https://github.com/dodyg/practical-aspnetcore/blob/3.1-LTS/projects/5-0/orleans/hello-world-2/silo/ but I am not clear how it relates to the publishing of this package.

**Comment by dodyg** [comment]
The new version works

`<PackageReference Include="Orleans.Persistence.Redis" Version="3.0.0" />`

![works](https://user-images.githubusercontent.com/1761249/89105375-cf4a0c80-d420-11ea-8034-b3100584cf3b.png)

**Comment by ReubenBond** [comment]
> I am not clear how it relates to the publishing of this package. 

Just so I can play around with what you're building 😁

**Comment by NikHusachenko** [comment]
I have a simple asp.net core web api templates with Orleans client and Orleans server. Client code:

```
var builder = WebApplication.CreateBuilder(args);
builder.Host
    .UseOrleansClient(client =>
    {
        client
            .UseRedisClustering("127.0.0.1:6379")
            .Configure<RedisClusteringOptions>(options =>
            {
                options.ConnectionString = "127.0.0.1:6379";
            });
    })
    .ConfigureLogging(logging => logging.AddConsole());

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(config =>
{
    config.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.UseCors();
app.Run();
```

And server code:
```
var builder = WebApplication.CreateBuilder(args);
builder.Host
    .UseOrleans(siloBuilder =>
    {
        siloBuilder
            .AddRedisGrainStorage("Redis")
            .UseRedisClustering("127.0.0.1:6379");
    })
    .ConfigureLogging(logging => logging.AddConsole());

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(config =>
{
    config.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.UseCors();
app.Run();
```

Then I tried to Multiple start projects and got exception:
`System.TypeLoadException: 'Could not load type 'Orleans.Runtime.KeyedServiceExtensions' from assembly 'Orleans.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.'`

How to resolve it?

**Comment by jkonecki** [comment]
Please take a look at this issue:
https://github.com/microsoft/ApplicationInsights-dotnet/issues/2828

The underlying problem is the order of service declarations. You will have
to tweak the order you add services in your Program.cs.
